### ISSUE TITLE
Server did not receive data, client freezes, waiting for a response

### ISSUE THREAD

**Issue by Yaisis** [shove70/async#1]
There was such a problem:
1) From the client, I sent data to the server with the socket.send function.
But the data did not reach the server.
2) Then the client is waiting for a response from the server with socket.receive function.
But since the data did not reach the server, he is not going to send anything back.
And the client freezes and waits.

What to do in such a situation?

**Comment by Yaisis** [comment]
I think I figured out how to solve the problem.
I'll try to put a timeout.

**Comment by shove70** [comment]
Yes, the client socket needs to set the receive timeout.

**Comment by shove70** [comment]
For example:
https://github.com/shove70/buffer/blob/master/libbuffer/src/buffer/rpc/client.d#L54

**Comment by Yaisis** [comment]
Thanks
